export default [

  { title: { i18n: 'home' }, name: 'home/home' },
  { title: '个人中心', name: 'own-space/own-space' },
  { title: '消息中心', name: 'message/message' },
  { title: '编辑商品', name: 'products/product-edit' },
  { title: '编辑类目', name: 'products/category-edit' },
  { title: '编辑合作商', name: 'contract/partner-management-edit' },
  { title: '新增海报', name: 'products/home-set-add' },
  { title: '新增活动', name: 'products/active-list-add' },
  { title: '新增资讯', name: 'products/information-list-add' },
  { title: '编辑合同政策', name: 'policy/policy-edit' },
  { title: '添加合同政策', name: 'policy/policy-add' },
  { title: '合同政策详情', name: 'policy/policy-detail' },
  { title: '编辑合作商政策', name: 'policy/policy-partner-edit' },
  // { title: '编辑订单审核', name:'order-management/audit-edit' },
  { title: '编辑现款现货订单', name: 'receipt/cash-edit' },
  { title: '编辑月结订单', name: 'receipt/month-edit' },
  { title: '编辑实销实报订单', name: 'receipt/actual-edit' },
  { title: '编辑订单审核', name: 'order-management/review-edit' },
  { title: '订单售后申请', name: 'order-management/order-service-apply' },
  { title: '订单退款申请', name: 'order-management/order-refund-apply' },
  { title: '详情', name: 'order-management/outside-calls-deliver-details' },
  { title: '订单详情', name: 'order-management/review-details' },
  { title: '商品详情', name: 'products/commodity-details-exhibition' },
  { title: '档案详情', name: 'employee-management/file-details' },
  { title: '添加团队', name: 'employee-management/add-team' },
  { title: '签到详情', name: 'field-management/attendance-details/default' },
  { title: '维护详情', name: 'field-management/attendance-details/maintain' },
  { title: '陌拜详情', name: 'field-management/attendance-details/moobei' },
  { title: '回访详情', name: 'field-management/attendance-details/visit' },
  { title: '巡店详情', name: 'field-management/attendance-details/tour' },
  { title: '贴柜详情', name: 'field-management/attendance-details/counter' },
  { title: '活动详情', name: 'field-management/attendance-details/activity' },
  // { title: '商家详情显示', name: 'contract/development-partner-management/development-details' },
  { title: '线索详情', name: 'contract/development-partner-management/development-details' },
  // { title: '确认合作', name: 'contract/development-partner-management/development-confirm' },
  { title: '线索转换', name: 'contract/development-partner-management/development-confirm' },
  { title: '线索编辑', name: 'contract/development-partner-management/development-edit' },
  { title: '合作商详情', name: 'contract/partner-management-detail' },
  { title: '编辑销售单', name: 'sale-order-management/sale-order-review/order-edit' },
  { title: '编辑库存单', name: 'store-order-management/store-order-review/order-edit' },
  { title: '编辑补发订单', name: 'order-management/review-replacement-edit' },
  { title: '补发详情', name: 'replacement-management/replacement-order-review/replacement-detail' },
  { title: '编辑样品订单', name: 'replacement-management/sample-order-review/sample-edit' },
  { title: '样品详情', name: 'replacement-management/sample-order-review/sample-detail' },

  { title: '商家详情', name: 'contract/customer-profile/info' },

  { title: '拆分订单', name:'order-management/order-split' },
  { title: '拆分补发订单', name:'order-delivery-management/replacement-deliver-split' },
  { title: '拆分样品订单', name:'order-delivery-management/sample-deliver-split' },

  { title: '编辑潜在客户', name: 'contract/potential-customer/customer-edit'},
  { title: '客户详情', name: 'contract/potential-customer/customer-detail'},
  { title: '合作客户详情', name: 'contract/cooperative-customer/cooperative-detail'},
  { title: '编辑合作客户', name: 'contract/cooperative-customer/cooperative-edit'},
  { title: '编辑门店', name: 'contract/facade/edit'},
  { title: '门店详情', name: 'contract/facade/detail'},

  // { path:'inform-management/notice-edit', title:'编辑通知', name:'inform-management/notice-edit'}

]
